{
 "title": "Sensores de localización",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "ID usuario",
    "query": "SELECT user_id FROM etlocationuser"
   },
   { "name": "timeRange", "label": "Granularidad", "query": "hour, day, week, month" }
  ]
 },
 "panels": [
  {
   "title": "Datos de usuario",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  entity_id,\n  uncertain,\n  user_id,\n  x1,\n  x2,\n  y1,\n  y2\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND user_id IN ($user_id)\nGROUP BY\n  time,\n  entity_id,\n  uncertain,\n  user_id,\n  x1,\n  x2,\n  y1,\n  y2\nORDER BY\n  time ASC\n\n  "
    }
   ]
  },
  {
   "title": "Gráfico temporal de líneas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) as time,\n  COUNT(*) AS \"metric\"\nFROM\n  etlocationuser\nWHERE\n  user_id IN ($user_id)\n  AND $__timeFilter(timestamp_sensor)\nGROUP BY\n  time\nORDER BY\n  time;\n\n\n  "
    }
   ]
  },
  {
   "title": "Heatmap - Distribución de usuarios",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) as time,\n  x1,\n  x2,\n  y1,\n  y2,\n  COUNT(*) as \"count\"\nFROM\n  etlocationuser\nWHERE\n  user_id IN ($user_id)\nGROUP BY\n  x1,\n  x2,\n  y1,\n  y2,\n  time\nORDER BY\n  time\n\n\n  "
    }
   ]
  },
  {
   "title": "Visualización de Incertidumbre",
   "type": "volkovlabs-echarts-panel",
   "description": "Se usan colores o tamaños de puntos para representar el nivel de incertidumbre en las mediciones donde los puntos con una incertidumbre baja son más grandes y de un color más intenso que los puntos con una incertidumbre alta.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) as \"time\",\n  x1 as \"x\",\n  y1 as \"y\",\n  uncertain,\n  user_id as \"user_id\"\nFROM\n  etlocationuser\nWHERE\n  user_id IN ($user_id) AND $__timeFilter(timestamp_sensor)\nGROUP BY\n  time,\n  x1,\n  y1,\n  uncertain,\n  user_id\nORDER BY\n  time ASC\n\n  "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  uncertain AS \"P1\" \nFROM \n  etlocationuser\nWHERE \n  $__timeFilter(timestamp_sensor) AND\n  (x1 BETWEEN 0 AND 25) AND \n  (x2 BETWEEN 0 AND 25) AND \n  (y1 BETWEEN 0 AND 25) AND \n  (y2 BETWEEN 0 AND 25)\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P2\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    x2 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y1 BETWEEN 0\n    AND 25\n  )\n  AND (\n    y2 BETWEEN 0\n    AND 25\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P3\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    x2 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y2 BETWEEN 26\n    AND 50\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P4\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 51\n    AND 100\n  )\n  AND (\n    x2 BETWEEN 51\n    AND 100\n  )\n  AND (\n    y1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y2 BETWEEN 26\n    AND 50\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P5\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 51\n    AND 100\n  )\n  AND (\n    x2 BETWEEN 51\n    AND 100\n  )\n  AND (\n    y1 BETWEEN 51\n    AND 100\n  )\n  AND (\n    y2 BETWEEN 51\n    AND 100\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Heatmap con distribución Gaussiana",
   "type": "volkovlabs-echarts-panel",
   "description": "Gaussiana: esta visualización utiliza una distribución gaussiana (o normal) para representar los datos. Es una curva suave con forma de campana donde el pico representa el valor más común y el ancho de la \"campana\" muestra cuánta variación hay en los datos. Esto es útil para mostrar cuánto varía una métrica con respecto al promedio.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\ndate_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  x1 as x1,\n  x2 as x2,\n  y1 as y1,\n  y2 as y2, \n  uncertain\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor) AND user_id IN ($user_id)\nGROUP BY\n  time,\n  x1,\n  x2,\n  y1,\n  y2,\n  uncertain\nORDER BY\n  time \n\n\n  "
    }
   ]
  },
  {
   "title": "Grafico de lineas",
   "type": "volkovlabs-echarts-panel",
   "description": "Eje x es una media de x1, x2\nEje Y es una media de y1,y2",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  x1,\n  x2,\n  y1,\n  y2\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND user_id IN ($user_id)\nGROUP BY\n  time,\n  x1,\n  x2,\n  y1,\n  y2\nORDER BY\n  time ASC\n\n  "
    }
   ]
  },
  {
   "title": "Gráficos de barras",
   "type": "barchart",
   "description": "muestren la actividad de los usuarios en función del tiempo o de otras variables relevantes. Esto te permitiría analizar el comportamiento de los usuarios en diferentes áreas. Puedes utilizar un gráfico de barras para visualizar la cantidad de registros de sensores por usuario, por hora del día o por área específica de la casa.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  user_id,\n  COUNT(*) AS activity\nFROM\n  etlocationuser\nWHERE $__timeFilter(timestamp_sensor) AND user_id IN ($user_id)\nGROUP BY\n  time,\n  user_id\nORDER BY\n  time;\n\n  "
    }
   ]
  }
 ]
}