{
 "title": "Sensores de localización",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "ID usuario",
    "query": "SELECT user_id FROM etlocationuser"
   },
   { "name": "timeRange", "label": "Granularidad", "query": "hour, day, week, month" }
  ]
 },
 "panels": [
  {
   "title": "Serie temporal de lineas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) as time,\n  COUNT(*) AS \"metric\"\nFROM\n  etlocationuser\n\nWHERE user_id IN ($user_id ) AND $__timeFilter(timestamp_sensor)\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Heatmap matriz",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    x1, \n    x2, \n    y1, \n    y2, \n    SUM(EXTRACT(EPOCH FROM timestamp_sensor)) as \"time\"\nFROM \n    etlocationuser\n    WHERE\n    user_id IN ($user_id )\nGROUP BY \n    x1, \n    x2, \n    y1, \n    y2"
    }
   ]
  },
  {
   "title": "Visualización de Incertidumbre",
   "type": "volkovlabs-echarts-panel",
   "description": "Se usan colores o tamaños de puntos para representar el nivel de incertidumbre en las mediciones donde los puntos con una incertidumbre baja son más grandes y de un color más intenso que los puntos con una incertidumbre alta.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) as \"time\",\n  x1 as \"x\",\n  y1 as \"y\",\n  uncertain,\n  user_id as \"user_id\"\nFROM\n  etlocationuser\nWHERE\n  user_id IN ($user_id) AND $__timeFilter(timestamp_sensor)\nGROUP BY\n  time,\n  x1,\n  y1,\n  uncertain,\n  user_id\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  uncertain AS \"P1\" \nFROM \n  etlocationuser\nWHERE \n  $__timeFilter(timestamp_sensor) AND\n  (x1 BETWEEN 0 AND 25) AND \n  (x2 BETWEEN 0 AND 25) AND \n  (y1 BETWEEN 0 AND 25) AND \n  (y2 BETWEEN 0 AND 25)\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P2\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    x2 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y1 BETWEEN 0\n    AND 25\n  )\n  AND (\n    y2 BETWEEN 0\n    AND 25\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P3\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    x2 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y2 BETWEEN 26\n    AND 50\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P4\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 51\n    AND 100\n  )\n  AND (\n    x2 BETWEEN 51\n    AND 100\n  )\n  AND (\n    y1 BETWEEN 26\n    AND 50\n  )\n  AND (\n    y2 BETWEEN 26\n    AND 50\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  uncertain AS \"P5\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND (\n    x1 BETWEEN 51\n    AND 100\n  )\n  AND (\n    x2 BETWEEN 51\n    AND 100\n  )\n  AND (\n    y1 BETWEEN 51\n    AND 100\n  )\n  AND (\n    y2 BETWEEN 51\n    AND 100\n  )\nGROUP BY\n  time,\n  uncertain\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "HeatMap",
   "type": "heatmap",
   "description": "densidad de puntos en un área específica. Este tipo de visualización te ayudaría a identificar áreas donde hay una mayor concentración de datos.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  COUNT(*) AS \"value\",\n  y1 AS \"latitude\",\n  x1 AS \"longitude\"\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\nGROUP BY\n  time,\n  y1,\n  x1\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Heatmap v3 -> Gaussian",
   "type": "volkovlabs-echarts-panel",
   "description": "Gaussiana: esta visualización utiliza una distribución gaussiana (o normal) para representar los datos. Es una curva suave con forma de campana donde el pico representa el valor más común y el ancho de la \"campana\" muestra cuánta variación hay en los datos. Esto es útil para mostrar cuánto varía una métrica con respecto al promedio.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\ndate_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  x1 as x1,\n  x2 as x2,\n  y1 as y1,\n  y2 as y2, \n  uncertain\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor) AND user_id IN ($user_id)\nGROUP BY\n  time,\n  x1,\n  x2,\n  y1,\n  y2,\n  uncertain\nORDER BY\n  time "
    }
   ]
  },
  {
   "title": "Grafico de lineas",
   "type": "volkovlabs-echarts-panel",
   "description": "Eje x es una media de x1, x2\nEje Y es una media de y1,y2",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  x1,\n  x2,\n  y1,\n  y2\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND user_id IN ($user_id)\nGROUP BY\n  time,\n  x1,\n  x2,\n  y1,\n  y2\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Gráficos de Barras o Líneas con Filtros de Usuarios",
   "type": "barchart",
   "description": "muestren la actividad de los usuarios en función del tiempo o de otras variables relevantes. Esto te permitiría analizar el comportamiento de los usuarios en diferentes áreas. Puedes utilizar un gráfico de barras para visualizar la cantidad de registros de sensores por usuario, por hora del día o por área específica de la casa.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  user_id,\n  COUNT(*) AS activity\nFROM\n  etlocationuser\nWHERE $__timeFilter(timestamp_sensor) AND user_id IN ($user_id)\nGROUP BY\n  time,\n  user_id\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  entity_id,\n  x1,\n  x2,\n  y1,\n  y2,\n  uncertain,\n  user_id\nFROM\n  etlocationuser\nWHERE\n  $__timeFilter(timestamp_sensor)\n  AND user_id IN ($user_id)\nGROUP BY\n  time,\n  entity_id,\n  x1,\n  x2,\n  y1,\n  y2,\n  uncertain,\n  user_id\nORDER BY\n  time ASC"
    }
   ]
  }
 ]
}