{
 "title": "Sensores binarios",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeRange", "label": "Granularidad", "query": "hour, day, week, month" }
  ]
 },
 "panels": [
  {
   "title": "Gráfico de pastel con porcentaje de tiempo activo vs inactivo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  CASE \n    WHEN activo = 0 THEN 'Inactivo'\n    WHEN activo = 1 THEN 'Activo'\n  END AS status,\n  COUNT(*) AS value\nFROM etbinarysensor\nWHERE\n  $__timeFilter(timestamp_sensor)\nGROUP BY \n  time,\n  status\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Gráfico de pastel de eventos por sensor activo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  count(*) AS \"Eventos\", \n  tipo_sensor\nFROM \n  etbinarySensor\nWHERE \n  $__timeFilter(timestamp_sensor) AND\n  activo = 1\nGROUP BY \n  time,\n  tipo_sensor\nORDER BY \n  time ASC"
    }
   ]
  },
  {
   "title": "Gráfico de barras de eventos por hora",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('$timeRange', timestamp_sensor) AS \"time\", count(*) AS \"Eventos\", tipo_sensor\nFROM etbinarysensor\nWHERE $__timeFilter(timestamp_sensor) AND activo = 1\nGROUP BY time, tipo_sensor\nORDER BY \"time\", \"Eventos\" DESC\n"
    }
   ]
  },
  {
   "title": "Contador de eventos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Eventos\", tipo_sensor\nFROM etbinarysensor\nWHERE activo = 1\nGROUP BY tipo_sensor\nORDER BY \"Eventos\" DESC\n\n\n"
    }
   ]
  },
  {
   "title": "Grafico de lineas de tiempo",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  activo, \n  tipo_sensor\nFROM \n  etbinarysensor\nWHERE \n  $__timeFilter(timestamp_sensor)\nGROUP BY \n  time,\n  activo, \n  tipo_sensor\nORDER BY \n  time ASC"
    }
   ]
  },
  {
   "title": "Grafico de lineas de tiempo 2",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  CASE \n    WHEN activo = 0 THEN 'Inactivo'\n    WHEN activo = 1 THEN 'Activo'\n  END AS activo, \n  tipo_sensor\nFROM \n  etbinarysensor\nWHERE \n  $__timeFilter(timestamp_sensor)\nGROUP BY \n  time,\n  activo, \n  tipo_sensor\nORDER BY \n  time ASC"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\", \n  tipo_sensor AS \"metric\", \n  activo\nFROM \n  etbinarysensor\nWHERE \n  $__timeFilter(timestamp_sensor)\nGROUP BY \n  time,\n  metric, \n  activo\nORDER BY \n  time ASC\n\n\n  "
    }
   ]
  },
  {
   "title": "Distribución de tipos de sensores",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('$timeRange', timestamp_sensor) AS \"time\",\n  tipo_sensor, \n  COUNT(*) as \" \" \nFROM \n  etbinarysensor\nWHERE \n  $__timeFilter(timestamp_sensor)\nGROUP BY \n  time,\n  tipo_sensor\nORDER BY \n  time ASC"
    }
   ]
  }
 ]
}