{
 "title": "Sensores binarios",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gráfico de pastel con porcentaje de tiempo activo vs inactivo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN activo = 0 THEN 'Inactivo'\n    WHEN activo = 1 THEN 'Activo'\n  END AS status,\n  COUNT(*) AS value\nFROM etbinarysensor\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Gráfico de pastel de eventos por sensor",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Eventos\", tipo_sensor\nFROM etbinarySensor\nWHERE activo = 1\nGROUP BY tipo_sensor\nORDER BY \"Eventos\" DESC"
    }
   ]
  },
  {
   "title": "Gráfico de barras de eventos por hora",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour', timestamp_sensor) AS \"time\", count(*) AS \"Eventos\", tipo_sensor\nFROM etbinarysensor\nWHERE activo = 1\nGROUP BY date_trunc('hour', timestamp_sensor), tipo_sensor\nORDER BY \"time\", \"Eventos\" DESC"
    }
   ]
  },
  {
   "title": "Contador de eventos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Eventos\", tipo_sensor\nFROM etbinarysensor\nWHERE activo = 1\nGROUP BY tipo_sensor\nORDER BY \"Eventos\" DESC"
    }
   ]
  },
  {
   "title": "Grafico de lineas de tiempo",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_sensor AS \"time\", activo, tipo_sensor\nFROM etbinarysensor\nORDER BY timestamp_sensor"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_sensor AS time, tipo_sensor AS metric, activo\nFROM etbinarysensor\nORDER BY timestamp_sensor ASC"
    }
   ]
  },
  {
   "title": "Distribución de tipos de sensores",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT tipo_sensor, COUNT(*) as total FROM etbinarysensor GROUP BY tipo_sensor"
    }
   ]
  }
 ]
}