{
 "title": "Sensores de localización",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "ID usuario",
    "query": "SELECT user_id FROM etlocationuser"
   }
  ]
 },
 "panels": [
  {
   "title": "Serie temporal de lineas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_sensor AS \"time\",\n  COUNT(*) AS \"metric\"\nFROM\n  etlocationuser\n\nWHERE user_id IN ($user_id )\nGROUP BY\n  timestamp_sensor\nORDER BY\n  timestamp_sensor;"
    }
   ]
  },
  {
   "title": "Heatmap matriz",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    x1, \n    x2, \n    y1, \n    y2, \n    SUM(EXTRACT(EPOCH FROM timestamp_sensor)) as \"time\"\nFROM \n    etlocationuser\n    WHERE\n    user_id IN ($user_id )\nGROUP BY \n    x1, \n    x2, \n    y1, \n    y2"
    }
   ]
  },
  {
   "title": "Visualización de Incertidumbre",
   "type": "volkovlabs-echarts-panel",
   "description": "Se usan colores o tamaños de puntos para representar el nivel de incertidumbre en las mediciones donde los puntos con una incertidumbre baja son más grandes y de un color más intenso que los puntos con una incertidumbre alta.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_sensor as \"time\",\n  x1 as \"x\",\n  y1 as \"y\",\n  uncertain,\n  user_id as \"user_id\"\nFROM\n  etlocationuser\nWHERE\n  user_id IN ($user_id)\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp_sensor AS \"time\", \n  uncertain AS \"P1\" \nFROM \n  etlocationuser\nWHERE (x1 BETWEEN 0 AND 25) AND (x2 BETWEEN 0 AND 25) AND (y1 BETWEEN 0 AND 25) AND (y2 BETWEEN 0 AND 25)\n"
    },
    {
     "rawSql": "SELECT \n  timestamp_sensor AS \"time\", \n  uncertain AS \"P2\" \nFROM \n  etlocationuser\nWHERE (x1 BETWEEN 26 AND 50) AND (x2 BETWEEN 26 AND 50) AND (y1 BETWEEN 0 AND 25) AND (y2 BETWEEN 0 AND 25)\n"
    },
    {
     "rawSql": "SELECT \n  timestamp_sensor AS \"time\", \n  uncertain AS \"P3\" \nFROM \n  etlocationuser\nWHERE (x1 BETWEEN 26 AND 50) AND (x2 BETWEEN 26 AND 50) AND (y1 BETWEEN 26 AND 50) AND (y2 BETWEEN 26 AND 50)\n"
    },
    {
     "rawSql": "SELECT timestamp_sensor AS \"time\", uncertain AS \"P4\" FROM etlocationuser \nWHERE (x1 BETWEEN 51 AND 100) AND (x2 BETWEEN 51 AND 100) AND (y1 BETWEEN 26 AND 50) AND (y2 BETWEEN 26 AND 50)\n"
    },
    {
     "rawSql": "SELECT timestamp_sensor AS \"time\", uncertain AS \"P5\" FROM etlocationuser\nWHERE (x1 BETWEEN 51 AND 100) AND (x2 BETWEEN 51 AND 100) AND (y1 BETWEEN 51 AND 100) AND (y2 BETWEEN 51 AND 100)\n"
    }
   ]
  },
  {
   "title": "HeatMap",
   "type": "heatmap",
   "description": "densidad de puntos en un área específica. Este tipo de visualización te ayudaría a identificar áreas donde hay una mayor concentración de datos.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(timestamp_sensor) AS \"time\",\n  COUNT(*) AS \"value\",\n  y1 AS \"latitude\",\n  x1 AS \"longitude\"\nFROM\n  etlocationuser\nGROUP BY\n  y1, x1"
    }
   ]
  },
  {
   "title": "Heatmap v3 -> Gaussian",
   "type": "volkovlabs-echarts-panel",
   "description": "Gaussiana: esta visualización utiliza una distribución gaussiana (o normal) para representar los datos. Es una curva suave con forma de campana donde el pico representa el valor más común y el ancho de la \"campana\" muestra cuánta variación hay en los datos. Esto es útil para mostrar cuánto varía una métrica con respecto al promedio.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  x1 as x1,\n  x2 as x2,\n  y1 as y1,\n  y2 as y2, \n  uncertain\nFROM\n  etlocationuser\nWHERE\n  user_id IN ($user_id)\nORDER BY\n  timestamp_sensor"
    }
   ]
  },
  {
   "title": "Grafico de lineas",
   "type": "volkovlabs-echarts-panel",
   "description": "Eje x es una media de x1, x2\nEje Y es una media de y1,y2",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_sensor, x1, x2, y1, y2\nFROM etlocationuser\nWHERE user_id IN ($user_id)\nORDER BY timestamp_sensor ASC;"
    }
   ]
  },
  {
   "title": "Gráficos de Barras o Líneas con Filtros de Usuarios",
   "type": "barchart",
   "description": "muestren la actividad de los usuarios en función del tiempo o de otras variables relevantes. Esto te permitiría analizar el comportamiento de los usuarios en diferentes áreas. Puedes utilizar un gráfico de barras para visualizar la cantidad de registros de sensores por usuario, por hora del día o por área específica de la casa.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', timestamp_sensor) AS time,\n  user_id,\n  COUNT(*) AS activity\nFROM\n  etlocationuser\nWHERE user_id IN ($user_id)\nGROUP BY\n  time,\n  user_id\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT entity_id, timestamp_sensor, x1, x2, y1, y2, uncertain, user_id FROM etlocationuser WHERE user_id IN ($user_id);"
    }
   ]
  }
 ]
}